sudo: required
language: python
python: "3.8"
cache: pip

install:
  - pip install awscli
  - pip install -r requirements/dev.txt
  - python setup.py install

script:
  - flake8
  - pytest
  - flake8

deploy:
  skip_cleanup: true
  provider: script
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  script: ./build_push_images.sh
  on:
    all_branches: true

