sudo: required
language: python
python: "3.8"
cache: pip

before_install:
  - pip install awscli

install:
  - pip install -r requirements/dev.txt
  - python setup.py install

jobs:
  include:
    - stage: Test
      script:
        - flake8
        - pytest

    - stage: Image deployment
      install: skip
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        access_key_id: $AWS_ACCESS_KEY_ID
        secret_access_key: $AWS_SECRET_ACCESS_KEY
        script: ./deployment/build_push_images.sh
        on:
          branch: main

    - stage: Github release
      before_install: skip
      install: skip
      script: skip
      before_deploy:
        - ./deployment/tag_commit.sh

      deploy:
        provider: releases
        skip_cleanup: true
        api_key: $GITHUB_TOKEN
        on:
          branch: main
