FROM python:3.8

ENV PYTHONPATH=/app
WORKDIR /app

ARG GITHUB_TOKEN
COPY /requirements/common.txt /requirements/common.txt
COPY /requirements/prod.txt /requirements/prod.txt
RUN pip install -r /requirements/prod.txt

COPY . .

RUN python setup.py install
