FROM valena_python

# Install JVM
RUN apt-get update --yes && \
    apt-get upgrade --yes && \
    apt-get install --yes default-jdk


# Fix certificate issues
RUN apt-get update && \
    apt-get install --yes ca-certificates-java && \
    update-ca-certificates -f;

RUN apt-get clean --yes

# Setup JAVA_HOME
ENV JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/

